CREATE TABLE IF NOT EXISTS `CONTACTS` (
  `CONTACT_ID` INTEGER PRIMARY KEY,
  `PRENOM` TEXT VARCHAR(50) NOT NULL,
  `NOM` TEXT VARCHAR(50) NOT NULL,
  `ADRESSE_EMAIL` TEXT VARCHAR(200) UNIQUE,
  `TELEPHONE` TELEPHONE TEXT CHECK (TELEPHONE GLOB '[0-9][0-9].[0-9][0-9].[0-9][0-9].[0-9][0-9].[0-9][0-9]')
)
